ARG RHCOS_VER
FROM ${RHCOS_VER}
RUN rpm-ostree uninstall kernel kernel-modules-extra kernel-modules kernel-modules-core kernel-core && \
    rpm-ostree install http://localhost/patch/kernel-{core-,modules-,modules-core-,modules-extra-}5.14.0-427.102.1.el9_4.x86_64.rpm && \
    rpm-ostree cleanup -m && \
    ostree container commit
