ARG RHCOS_VER
FROM ${RHCOS_VER}
RUN rpm-ostree uninstall kernel && \ 
    rpm-ostree override replace http://localhost/patch/kernel-{core-,devel-,headers-,modules-,modules-core-,modules-extra-,modules-internal-}5.14.0-427.62.1.rhel83455_cpuset.el9_4.x86_64.rpm && \
    rpm-ostree cleanup -m && \
    ostree container commit
